/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'petCreation': MotiaStream<{ message: string }>
  }

  interface Handlers {
    'JsSetNextFeedingReminder': EventHandler<never, { topic: 'js.feeding.reminder.completed2'; data: never }>
    'JsCreatePet': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'js.pet.created2'; data: never } | { topic: 'js.feeding.reminder.enqueued2'; data: never }>
    'JsAiProfileEnrichment': EventHandler<never, never>
    'GetPets': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DeletePet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'JsDeletionReaper': CronHandler<never>
    'CreatePet': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'js.feeding.reminder.enqueued'; data: never }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'JsPetLifecycleOrchestrator': EventHandler<never, never>
    'UpdatePet': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}